name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Make init
      run: make init

    - name: Make docker-build
      env:
        IMAGE_NAME: devopsclass-app
      run: make docker-build

    - name: Make run
      env:
        IMAGE_NAME: devopsclass-app
        PORT: 5000
      run: make run

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: DevopsClass
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
